/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AlbumDto,
    AlbumDtoFromJSON,
    AlbumDtoToJSON,
} from '../models/AlbumDto';
import {
    type AllMusicDto,
    AllMusicDtoFromJSON,
    AllMusicDtoToJSON,
} from '../models/AllMusicDto';
import {
    type ErrorResponseDto,
    ErrorResponseDtoFromJSON,
    ErrorResponseDtoToJSON,
} from '../models/ErrorResponseDto';
import {
    type ExploreEntryDto,
    ExploreEntryDtoFromJSON,
    ExploreEntryDtoToJSON,
} from '../models/ExploreEntryDto';
import {
    type PlaylistDto,
    PlaylistDtoFromJSON,
    PlaylistDtoToJSON,
} from '../models/PlaylistDto';

export interface AddSongToPlaylistRequest {
    songId: number;
    playlistId: number;
}

export interface CreatePlaylistRequest {
    playlistName: string;
    file?: Blob;
}

export interface DeletePlaylistRequest {
    playlistId: number;
}

export interface DeleteSongFromPlaylistRequest {
    songId: number;
    playlistId: number;
}

/**
 * 
 */
export class MusicPlayControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for addSongToPlaylist without sending the request
     */
    async addSongToPlaylistRequestOpts(requestParameters: AddSongToPlaylistRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['songId'] == null) {
            throw new runtime.RequiredError(
                'songId',
                'Required parameter "songId" was null or undefined when calling addSongToPlaylist().'
            );
        }

        if (requestParameters['playlistId'] == null) {
            throw new runtime.RequiredError(
                'playlistId',
                'Required parameter "playlistId" was null or undefined when calling addSongToPlaylist().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['songId'] != null) {
            queryParameters['songId'] = requestParameters['songId'];
        }

        if (requestParameters['playlistId'] != null) {
            queryParameters['playlistId'] = requestParameters['playlistId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/addSongToPlaylist`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Add song to a specific playlist
     */
    async addSongToPlaylistRaw(requestParameters: AddSongToPlaylistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.addSongToPlaylistRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Add song to a specific playlist
     */
    async addSongToPlaylist(requestParameters: AddSongToPlaylistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.addSongToPlaylistRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for createPlaylist without sending the request
     */
    async createPlaylistRequestOpts(requestParameters: CreatePlaylistRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['playlistName'] == null) {
            throw new runtime.RequiredError(
                'playlistName',
                'Required parameter "playlistName" was null or undefined when calling createPlaylist().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['playlistName'] != null) {
            queryParameters['playlistName'] = requestParameters['playlistName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/api/v1/createPlaylist`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Create a playlist
     */
    async createPlaylistRaw(requestParameters: CreatePlaylistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.createPlaylistRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a playlist
     */
    async createPlaylist(requestParameters: CreatePlaylistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createPlaylistRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deletePlaylist without sending the request
     */
    async deletePlaylistRequestOpts(requestParameters: DeletePlaylistRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['playlistId'] == null) {
            throw new runtime.RequiredError(
                'playlistId',
                'Required parameter "playlistId" was null or undefined when calling deletePlaylist().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['playlistId'] != null) {
            queryParameters['playlistId'] = requestParameters['playlistId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/deletePlaylist`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a playlist
     */
    async deletePlaylistRaw(requestParameters: DeletePlaylistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deletePlaylistRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a playlist
     */
    async deletePlaylist(requestParameters: DeletePlaylistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePlaylistRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteSongFromPlaylist without sending the request
     */
    async deleteSongFromPlaylistRequestOpts(requestParameters: DeleteSongFromPlaylistRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['songId'] == null) {
            throw new runtime.RequiredError(
                'songId',
                'Required parameter "songId" was null or undefined when calling deleteSongFromPlaylist().'
            );
        }

        if (requestParameters['playlistId'] == null) {
            throw new runtime.RequiredError(
                'playlistId',
                'Required parameter "playlistId" was null or undefined when calling deleteSongFromPlaylist().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['songId'] != null) {
            queryParameters['songId'] = requestParameters['songId'];
        }

        if (requestParameters['playlistId'] != null) {
            queryParameters['playlistId'] = requestParameters['playlistId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/deleteSongFromPlaylist`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete song from a specific playlist
     */
    async deleteSongFromPlaylistRaw(requestParameters: DeleteSongFromPlaylistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteSongFromPlaylistRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete song from a specific playlist
     */
    async deleteSongFromPlaylist(requestParameters: DeleteSongFromPlaylistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteSongFromPlaylistRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getAlbums without sending the request
     */
    async getAlbumsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/getAlbums`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all albums
     */
    async getAlbumsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AlbumDto>>> {
        const requestOptions = await this.getAlbumsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AlbumDtoFromJSON));
    }

    /**
     * Get all albums
     */
    async getAlbums(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AlbumDto>> {
        const response = await this.getAlbumsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAllMusic without sending the request
     */
    async getAllMusicRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/getAllMusic`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all music of library entire
     */
    async getAllMusicRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AllMusicDto>>> {
        const requestOptions = await this.getAllMusicRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AllMusicDtoFromJSON));
    }

    /**
     * Get all music of library entire
     */
    async getAllMusic(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AllMusicDto>> {
        const response = await this.getAllMusicRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getExploreFeed without sending the request
     */
    async getExploreFeedRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/getExploreFeed`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get explore feed
     */
    async getExploreFeedRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ExploreEntryDto>>> {
        const requestOptions = await this.getExploreFeedRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ExploreEntryDtoFromJSON));
    }

    /**
     * Get explore feed
     */
    async getExploreFeed(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ExploreEntryDto>> {
        const response = await this.getExploreFeedRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPlaylists without sending the request
     */
    async getPlaylistsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/getPlaylists`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all playlists from user
     */
    async getPlaylistsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PlaylistDto>>> {
        const requestOptions = await this.getPlaylistsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PlaylistDtoFromJSON));
    }

    /**
     * Get all playlists from user
     */
    async getPlaylists(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PlaylistDto>> {
        const response = await this.getPlaylistsRaw(initOverrides);
        return await response.value();
    }

}
