/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AlbumListDto,
    AlbumListDtoFromJSON,
    AlbumListDtoToJSON,
} from '../models/AlbumListDto';
import {
    type PlaylistListDto,
    PlaylistListDtoFromJSON,
    PlaylistListDtoToJSON,
} from '../models/PlaylistListDto';

export interface AddSongToPlaylistRequest {
    songId: number;
    playlistId: number;
}

export interface CreatePlaylistRequest {
    playlistName: string;
}

export interface DeletePlaylistRequest {
    playlistId: number;
}

export interface RemoveSongFromPlaylistRequest {
    songId: number;
    playlistId: number;
}

/**
 * 
 */
export class MusicPlayControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for addSongToPlaylist without sending the request
     */
    async addSongToPlaylistRequestOpts(requestParameters: AddSongToPlaylistRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['songId'] == null) {
            throw new runtime.RequiredError(
                'songId',
                'Required parameter "songId" was null or undefined when calling addSongToPlaylist().'
            );
        }

        if (requestParameters['playlistId'] == null) {
            throw new runtime.RequiredError(
                'playlistId',
                'Required parameter "playlistId" was null or undefined when calling addSongToPlaylist().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['songId'] != null) {
            queryParameters['songId'] = requestParameters['songId'];
        }

        if (requestParameters['playlistId'] != null) {
            queryParameters['playlistId'] = requestParameters['playlistId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/addSongToPlaylist`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Add song to a specific playlist
     */
    async addSongToPlaylistRaw(requestParameters: AddSongToPlaylistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.addSongToPlaylistRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Add song to a specific playlist
     */
    async addSongToPlaylist(requestParameters: AddSongToPlaylistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.addSongToPlaylistRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for createPlaylist without sending the request
     */
    async createPlaylistRequestOpts(requestParameters: CreatePlaylistRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['playlistName'] == null) {
            throw new runtime.RequiredError(
                'playlistName',
                'Required parameter "playlistName" was null or undefined when calling createPlaylist().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['playlistName'] != null) {
            queryParameters['playlistName'] = requestParameters['playlistName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/createPlaylist`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Create a playlist
     */
    async createPlaylistRaw(requestParameters: CreatePlaylistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.createPlaylistRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a playlist
     */
    async createPlaylist(requestParameters: CreatePlaylistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createPlaylistRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deletePlaylist without sending the request
     */
    async deletePlaylistRequestOpts(requestParameters: DeletePlaylistRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['playlistId'] == null) {
            throw new runtime.RequiredError(
                'playlistId',
                'Required parameter "playlistId" was null or undefined when calling deletePlaylist().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['playlistId'] != null) {
            queryParameters['playlistId'] = requestParameters['playlistId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/deletePlaylist`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a playlist
     */
    async deletePlaylistRaw(requestParameters: DeletePlaylistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deletePlaylistRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a playlist
     */
    async deletePlaylist(requestParameters: DeletePlaylistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePlaylistRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getAlbums without sending the request
     */
    async getAlbumsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/getAlbums`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all albums
     */
    async getAlbumsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlbumListDto>> {
        const requestOptions = await this.getAlbumsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlbumListDtoFromJSON(jsonValue));
    }

    /**
     * Get all albums
     */
    async getAlbums(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlbumListDto> {
        const response = await this.getAlbumsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPlaylists without sending the request
     */
    async getPlaylistsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/getPlaylists`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all playlists from user
     */
    async getPlaylistsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaylistListDto>> {
        const requestOptions = await this.getPlaylistsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaylistListDtoFromJSON(jsonValue));
    }

    /**
     * Get all playlists from user
     */
    async getPlaylists(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaylistListDto> {
        const response = await this.getPlaylistsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for removeSongFromPlaylist without sending the request
     */
    async removeSongFromPlaylistRequestOpts(requestParameters: RemoveSongFromPlaylistRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['songId'] == null) {
            throw new runtime.RequiredError(
                'songId',
                'Required parameter "songId" was null or undefined when calling removeSongFromPlaylist().'
            );
        }

        if (requestParameters['playlistId'] == null) {
            throw new runtime.RequiredError(
                'playlistId',
                'Required parameter "playlistId" was null or undefined when calling removeSongFromPlaylist().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['songId'] != null) {
            queryParameters['songId'] = requestParameters['songId'];
        }

        if (requestParameters['playlistId'] != null) {
            queryParameters['playlistId'] = requestParameters['playlistId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/removeSongFromPlaylist`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Removes song from a specific playlist
     */
    async removeSongFromPlaylistRaw(requestParameters: RemoveSongFromPlaylistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.removeSongFromPlaylistRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes song from a specific playlist
     */
    async removeSongFromPlaylist(requestParameters: RemoveSongFromPlaylistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.removeSongFromPlaylistRaw(requestParameters, initOverrides);
    }

}
