/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountCreateDto
 */
export interface AccountCreateDto {
    /**
     * 
     * @type {string}
     * @memberof AccountCreateDto
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof AccountCreateDto
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof AccountCreateDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AccountCreateDto
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof AccountCreateDto
     */
    lastName: string;
}

/**
 * Check if a given object implements the AccountCreateDto interface.
 */
export function instanceOfAccountCreateDto(value: object): value is AccountCreateDto {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    return true;
}

export function AccountCreateDtoFromJSON(json: any): AccountCreateDto {
    return AccountCreateDtoFromJSONTyped(json, false);
}

export function AccountCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
        'email': json['email'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
    };
}

export function AccountCreateDtoToJSON(json: any): AccountCreateDto {
    return AccountCreateDtoToJSONTyped(json, false);
}

export function AccountCreateDtoToJSONTyped(value?: AccountCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
        'email': value['email'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
    };
}

