/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountEditDto
 */
export interface AccountEditDto {
    /**
     * 
     * @type {string}
     * @memberof AccountEditDto
     */
    username: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof AccountEditDto
     */
    edits: { [key: string]: string; };
}

/**
 * Check if a given object implements the AccountEditDto interface.
 */
export function instanceOfAccountEditDto(value: object): value is AccountEditDto {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('edits' in value) || value['edits'] === undefined) return false;
    return true;
}

export function AccountEditDtoFromJSON(json: any): AccountEditDto {
    return AccountEditDtoFromJSONTyped(json, false);
}

export function AccountEditDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountEditDto {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'edits': json['edits'],
    };
}

export function AccountEditDtoToJSON(json: any): AccountEditDto {
    return AccountEditDtoToJSONTyped(json, false);
}

export function AccountEditDtoToJSONTyped(value?: AccountEditDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'edits': value['edits'],
    };
}

