/* tslint:disable */
/* eslint-disable */
/**
 * Music Play API
 * Used for the querying of account/music services.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SongDto } from './SongDto';
import {
    SongDtoFromJSON,
    SongDtoFromJSONTyped,
    SongDtoToJSON,
    SongDtoToJSONTyped,
} from './SongDto';

/**
 * 
 * @export
 * @interface AlbumDto
 */
export interface AlbumDto {
    /**
     * 
     * @type {string}
     * @memberof AlbumDto
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof AlbumDto
     */
    coverPath?: string;
    /**
     * 
     * @type {number}
     * @memberof AlbumDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AlbumDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AlbumDto
     */
    artistName?: string;
    /**
     * 
     * @type {number}
     * @memberof AlbumDto
     */
    artistId?: number;
    /**
     * 
     * @type {Array<SongDto>}
     * @memberof AlbumDto
     */
    songs?: Array<SongDto>;
}

/**
 * Check if a given object implements the AlbumDto interface.
 */
export function instanceOfAlbumDto(value: object): value is AlbumDto {
    return true;
}

export function AlbumDtoFromJSON(json: any): AlbumDto {
    return AlbumDtoFromJSONTyped(json, false);
}

export function AlbumDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlbumDto {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'coverPath': json['coverPath'] == null ? undefined : json['coverPath'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'artistName': json['artistName'] == null ? undefined : json['artistName'],
        'artistId': json['artistId'] == null ? undefined : json['artistId'],
        'songs': json['songs'] == null ? undefined : ((json['songs'] as Array<any>).map(SongDtoFromJSON)),
    };
}

export function AlbumDtoToJSON(json: any): AlbumDto {
    return AlbumDtoToJSONTyped(json, false);
}

export function AlbumDtoToJSONTyped(value?: AlbumDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'coverPath': value['coverPath'],
        'id': value['id'],
        'name': value['name'],
        'artistName': value['artistName'],
        'artistId': value['artistId'],
        'songs': value['songs'] == null ? undefined : ((value['songs'] as Array<any>).map(SongDtoToJSON)),
    };
}

