/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AlbumDto } from './AlbumDto';
import {
    AlbumDtoFromJSON,
    AlbumDtoFromJSONTyped,
    AlbumDtoToJSON,
    AlbumDtoToJSONTyped,
} from './AlbumDto';

/**
 * 
 * @export
 * @interface AlbumListDto
 */
export interface AlbumListDto {
    /**
     * 
     * @type {Array<AlbumDto>}
     * @memberof AlbumListDto
     */
    albums?: Array<AlbumDto>;
}

/**
 * Check if a given object implements the AlbumListDto interface.
 */
export function instanceOfAlbumListDto(value: object): value is AlbumListDto {
    return true;
}

export function AlbumListDtoFromJSON(json: any): AlbumListDto {
    return AlbumListDtoFromJSONTyped(json, false);
}

export function AlbumListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlbumListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'albums': json['albums'] == null ? undefined : ((json['albums'] as Array<any>).map(AlbumDtoFromJSON)),
    };
}

export function AlbumListDtoToJSON(json: any): AlbumListDto {
    return AlbumListDtoToJSONTyped(json, false);
}

export function AlbumListDtoToJSONTyped(value?: AlbumListDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'albums': value['albums'] == null ? undefined : ((value['albums'] as Array<any>).map(AlbumDtoToJSON)),
    };
}

