/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AlbumDto } from './AlbumDto';
import {
    AlbumDtoFromJSON,
    AlbumDtoFromJSONTyped,
    AlbumDtoToJSON,
    AlbumDtoToJSONTyped,
} from './AlbumDto';

/**
 * 
 * @export
 * @interface AllMusicDto
 */
export interface AllMusicDto {
    /**
     * 
     * @type {string}
     * @memberof AllMusicDto
     */
    artistName?: string;
    /**
     * 
     * @type {Array<AlbumDto>}
     * @memberof AllMusicDto
     */
    albums?: Array<AlbumDto>;
}

/**
 * Check if a given object implements the AllMusicDto interface.
 */
export function instanceOfAllMusicDto(value: object): value is AllMusicDto {
    return true;
}

export function AllMusicDtoFromJSON(json: any): AllMusicDto {
    return AllMusicDtoFromJSONTyped(json, false);
}

export function AllMusicDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllMusicDto {
    if (json == null) {
        return json;
    }
    return {
        
        'artistName': json['artistName'] == null ? undefined : json['artistName'],
        'albums': json['albums'] == null ? undefined : ((json['albums'] as Array<any>).map(AlbumDtoFromJSON)),
    };
}

export function AllMusicDtoToJSON(json: any): AllMusicDto {
    return AllMusicDtoToJSONTyped(json, false);
}

export function AllMusicDtoToJSONTyped(value?: AllMusicDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'artistName': value['artistName'],
        'albums': value['albums'] == null ? undefined : ((value['albums'] as Array<any>).map(AlbumDtoToJSON)),
    };
}

