/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppUserDto
 */
export interface AppUserDto {
    /**
     * 
     * @type {string}
     * @memberof AppUserDto
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof AppUserDto
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof AppUserDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof AppUserDto
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof AppUserDto
     */
    lastName?: string;
}

/**
 * Check if a given object implements the AppUserDto interface.
 */
export function instanceOfAppUserDto(value: object): value is AppUserDto {
    return true;
}

export function AppUserDtoFromJSON(json: any): AppUserDto {
    return AppUserDtoFromJSONTyped(json, false);
}

export function AppUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'password': json['password'] == null ? undefined : json['password'],
        'email': json['email'] == null ? undefined : json['email'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
    };
}

export function AppUserDtoToJSON(json: any): AppUserDto {
    return AppUserDtoToJSONTyped(json, false);
}

export function AppUserDtoToJSONTyped(value?: AppUserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
        'email': value['email'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
    };
}

