/* tslint:disable */
/* eslint-disable */
/**
 * Music Play API
 * Used for the querying of account/music services.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AlbumDto } from './AlbumDto';
import {
    AlbumDtoFromJSON,
    AlbumDtoFromJSONTyped,
    AlbumDtoToJSON,
    AlbumDtoToJSONTyped,
} from './AlbumDto';

/**
 * 
 * @export
 * @interface ArtistDto
 */
export interface ArtistDto {
    /**
     * 
     * @type {string}
     * @memberof ArtistDto
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ArtistDto
     */
    coverPath?: string;
    /**
     * 
     * @type {string}
     * @memberof ArtistDto
     */
    name?: string;
    /**
     * 
     * @type {Array<AlbumDto>}
     * @memberof ArtistDto
     */
    albums?: Array<AlbumDto>;
}

/**
 * Check if a given object implements the ArtistDto interface.
 */
export function instanceOfArtistDto(value: object): value is ArtistDto {
    return true;
}

export function ArtistDtoFromJSON(json: any): ArtistDto {
    return ArtistDtoFromJSONTyped(json, false);
}

export function ArtistDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtistDto {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'coverPath': json['coverPath'] == null ? undefined : json['coverPath'],
        'name': json['name'] == null ? undefined : json['name'],
        'albums': json['albums'] == null ? undefined : ((json['albums'] as Array<any>).map(AlbumDtoFromJSON)),
    };
}

export function ArtistDtoToJSON(json: any): ArtistDto {
    return ArtistDtoToJSONTyped(json, false);
}

export function ArtistDtoToJSONTyped(value?: ArtistDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'coverPath': value['coverPath'],
        'name': value['name'],
        'albums': value['albums'] == null ? undefined : ((value['albums'] as Array<any>).map(AlbumDtoToJSON)),
    };
}

