/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditLastNameDto
 */
export interface EditLastNameDto {
    /**
     * 
     * @type {string}
     * @memberof EditLastNameDto
     */
    lastName: string;
}

/**
 * Check if a given object implements the EditLastNameDto interface.
 */
export function instanceOfEditLastNameDto(value: object): value is EditLastNameDto {
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    return true;
}

export function EditLastNameDtoFromJSON(json: any): EditLastNameDto {
    return EditLastNameDtoFromJSONTyped(json, false);
}

export function EditLastNameDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditLastNameDto {
    if (json == null) {
        return json;
    }
    return {
        
        'lastName': json['lastName'],
    };
}

export function EditLastNameDtoToJSON(json: any): EditLastNameDto {
    return EditLastNameDtoToJSONTyped(json, false);
}

export function EditLastNameDtoToJSONTyped(value?: EditLastNameDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lastName': value['lastName'],
    };
}

