/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditEmailDto
 */
export interface EditEmailDto {
    /**
     * 
     * @type {string}
     * @memberof EditEmailDto
     */
    email: string;
}

/**
 * Check if a given object implements the EditEmailDto interface.
 */
export function instanceOfEditEmailDto(value: object): value is EditEmailDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function EditEmailDtoFromJSON(json: any): EditEmailDto {
    return EditEmailDtoFromJSONTyped(json, false);
}

export function EditEmailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditEmailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function EditEmailDtoToJSON(json: any): EditEmailDto {
    return EditEmailDtoToJSONTyped(json, false);
}

export function EditEmailDtoToJSONTyped(value?: EditEmailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

