/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditFirstNameDto
 */
export interface EditFirstNameDto {
    /**
     * 
     * @type {string}
     * @memberof EditFirstNameDto
     */
    firstName: string;
}

/**
 * Check if a given object implements the EditFirstNameDto interface.
 */
export function instanceOfEditFirstNameDto(value: object): value is EditFirstNameDto {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    return true;
}

export function EditFirstNameDtoFromJSON(json: any): EditFirstNameDto {
    return EditFirstNameDtoFromJSONTyped(json, false);
}

export function EditFirstNameDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditFirstNameDto {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
    };
}

export function EditFirstNameDtoToJSON(json: any): EditFirstNameDto {
    return EditFirstNameDtoToJSONTyped(json, false);
}

export function EditFirstNameDtoToJSONTyped(value?: EditFirstNameDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
    };
}

