/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditUsernameDto
 */
export interface EditUsernameDto {
    /**
     * 
     * @type {string}
     * @memberof EditUsernameDto
     */
    username: string;
}

/**
 * Check if a given object implements the EditUsernameDto interface.
 */
export function instanceOfEditUsernameDto(value: object): value is EditUsernameDto {
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function EditUsernameDtoFromJSON(json: any): EditUsernameDto {
    return EditUsernameDtoFromJSONTyped(json, false);
}

export function EditUsernameDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditUsernameDto {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
    };
}

export function EditUsernameDtoToJSON(json: any): EditUsernameDto {
    return EditUsernameDtoToJSONTyped(json, false);
}

export function EditUsernameDtoToJSONTyped(value?: EditUsernameDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
    };
}

