/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditPasswordDto
 */
export interface EditPasswordDto {
    /**
     * 
     * @type {string}
     * @memberof EditPasswordDto
     */
    password: string;
}

/**
 * Check if a given object implements the EditPasswordDto interface.
 */
export function instanceOfEditPasswordDto(value: object): value is EditPasswordDto {
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function EditPasswordDtoFromJSON(json: any): EditPasswordDto {
    return EditPasswordDtoFromJSONTyped(json, false);
}

export function EditPasswordDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditPasswordDto {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'],
    };
}

export function EditPasswordDtoToJSON(json: any): EditPasswordDto {
    return EditPasswordDtoToJSONTyped(json, false);
}

export function EditPasswordDtoToJSONTyped(value?: EditPasswordDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
    };
}

