/* tslint:disable */
/* eslint-disable */
/**
 * Music Play API
 * Used for the querying of account/music services.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorResponseDto
 */
export interface ErrorResponseDto {
    /**
     * 
     * @type {Date}
     * @memberof ErrorResponseDto
     */
    time?: Date;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseDto
     */
    message?: string;
}

/**
 * Check if a given object implements the ErrorResponseDto interface.
 */
export function instanceOfErrorResponseDto(value: object): value is ErrorResponseDto {
    return true;
}

export function ErrorResponseDtoFromJSON(json: any): ErrorResponseDto {
    return ErrorResponseDtoFromJSONTyped(json, false);
}

export function ErrorResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'time': json['time'] == null ? undefined : (new Date(json['time'])),
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ErrorResponseDtoToJSON(json: any): ErrorResponseDto {
    return ErrorResponseDtoToJSONTyped(json, false);
}

export function ErrorResponseDtoToJSONTyped(value?: ErrorResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time': value['time'] == null ? value['time'] : value['time'].toISOString(),
        'message': value['message'],
    };
}

