/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlaylistDto } from './PlaylistDto';
import {
    PlaylistDtoFromJSON,
    PlaylistDtoFromJSONTyped,
    PlaylistDtoToJSON,
    PlaylistDtoToJSONTyped,
} from './PlaylistDto';

/**
 * 
 * @export
 * @interface ExploreEntryDto
 */
export interface ExploreEntryDto {
    /**
     * 
     * @type {string}
     * @memberof ExploreEntryDto
     */
    label?: string;
    /**
     * 
     * @type {Array<PlaylistDto>}
     * @memberof ExploreEntryDto
     */
    feed?: Array<PlaylistDto>;
}

/**
 * Check if a given object implements the ExploreEntryDto interface.
 */
export function instanceOfExploreEntryDto(value: object): value is ExploreEntryDto {
    return true;
}

export function ExploreEntryDtoFromJSON(json: any): ExploreEntryDto {
    return ExploreEntryDtoFromJSONTyped(json, false);
}

export function ExploreEntryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExploreEntryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'] == null ? undefined : json['label'],
        'feed': json['feed'] == null ? undefined : ((json['feed'] as Array<any>).map(PlaylistDtoFromJSON)),
    };
}

export function ExploreEntryDtoToJSON(json: any): ExploreEntryDto {
    return ExploreEntryDtoToJSONTyped(json, false);
}

export function ExploreEntryDtoToJSONTyped(value?: ExploreEntryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'feed': value['feed'] == null ? undefined : ((value['feed'] as Array<any>).map(PlaylistDtoToJSON)),
    };
}

