/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlaylistDto } from './PlaylistDto';
import {
    PlaylistDtoFromJSON,
    PlaylistDtoFromJSONTyped,
    PlaylistDtoToJSON,
    PlaylistDtoToJSONTyped,
} from './PlaylistDto';

/**
 * 
 * @export
 * @interface ExploreFeedDto
 */
export interface ExploreFeedDto {
    /**
     * 
     * @type {{ [key: string]: Array<PlaylistDto>; }}
     * @memberof ExploreFeedDto
     */
    feed?: { [key: string]: Array<PlaylistDto>; };
}

/**
 * Check if a given object implements the ExploreFeedDto interface.
 */
export function instanceOfExploreFeedDto(value: object): value is ExploreFeedDto {
    return true;
}

export function ExploreFeedDtoFromJSON(json: any): ExploreFeedDto {
    return ExploreFeedDtoFromJSONTyped(json, false);
}

export function ExploreFeedDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExploreFeedDto {
    if (json == null) {
        return json;
    }
    return {
        
        'feed': json['feed'] == null ? undefined : json['feed'],
    };
}

export function ExploreFeedDtoToJSON(json: any): ExploreFeedDto {
    return ExploreFeedDtoToJSONTyped(json, false);
}

export function ExploreFeedDtoToJSONTyped(value?: ExploreFeedDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'feed': value['feed'],
    };
}

