/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlaylistDto } from './PlaylistDto';
import {
    PlaylistDtoFromJSON,
    PlaylistDtoFromJSONTyped,
    PlaylistDtoToJSON,
    PlaylistDtoToJSONTyped,
} from './PlaylistDto';

/**
 * 
 * @export
 * @interface PlaylistListDto
 */
export interface PlaylistListDto {
    /**
     * 
     * @type {Array<PlaylistDto>}
     * @memberof PlaylistListDto
     */
    playlists?: Array<PlaylistDto>;
}

/**
 * Check if a given object implements the PlaylistListDto interface.
 */
export function instanceOfPlaylistListDto(value: object): value is PlaylistListDto {
    return true;
}

export function PlaylistListDtoFromJSON(json: any): PlaylistListDto {
    return PlaylistListDtoFromJSONTyped(json, false);
}

export function PlaylistListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaylistListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'playlists': json['playlists'] == null ? undefined : ((json['playlists'] as Array<any>).map(PlaylistDtoFromJSON)),
    };
}

export function PlaylistListDtoToJSON(json: any): PlaylistListDto {
    return PlaylistListDtoToJSONTyped(json, false);
}

export function PlaylistListDtoToJSONTyped(value?: PlaylistListDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'playlists': value['playlists'] == null ? undefined : ((value['playlists'] as Array<any>).map(PlaylistDtoToJSON)),
    };
}

