/* tslint:disable */
/* eslint-disable */
/**
 * Music Play API
 * Used for the querying of account/music services.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SongDto } from './SongDto';
import {
    SongDtoFromJSON,
    SongDtoFromJSONTyped,
    SongDtoToJSON,
    SongDtoToJSONTyped,
} from './SongDto';

/**
 * 
 * @export
 * @interface PlaylistDto
 */
export interface PlaylistDto {
    /**
     * 
     * @type {number}
     * @memberof PlaylistDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PlaylistDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaylistDto
     */
    coverPath?: string;
    /**
     * 
     * @type {Array<SongDto>}
     * @memberof PlaylistDto
     */
    songs?: Array<SongDto>;
}

/**
 * Check if a given object implements the PlaylistDto interface.
 */
export function instanceOfPlaylistDto(value: object): value is PlaylistDto {
    return true;
}

export function PlaylistDtoFromJSON(json: any): PlaylistDto {
    return PlaylistDtoFromJSONTyped(json, false);
}

export function PlaylistDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaylistDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'coverPath': json['coverPath'] == null ? undefined : json['coverPath'],
        'songs': json['songs'] == null ? undefined : ((json['songs'] as Array<any>).map(SongDtoFromJSON)),
    };
}

export function PlaylistDtoToJSON(json: any): PlaylistDto {
    return PlaylistDtoToJSONTyped(json, false);
}

export function PlaylistDtoToJSONTyped(value?: PlaylistDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'coverPath': value['coverPath'],
        'songs': value['songs'] == null ? undefined : ((value['songs'] as Array<any>).map(SongDtoToJSON)),
    };
}

