/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SongDto } from './SongDto';
import {
    SongDtoFromJSON,
    SongDtoFromJSONTyped,
    SongDtoToJSON,
    SongDtoToJSONTyped,
} from './SongDto';
import type { AlbumDto } from './AlbumDto';
import {
    AlbumDtoFromJSON,
    AlbumDtoFromJSONTyped,
    AlbumDtoToJSON,
    AlbumDtoToJSONTyped,
} from './AlbumDto';

/**
 * 
 * @export
 * @interface SearchResponseDto
 */
export interface SearchResponseDto {
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchResponseDto
     */
    artists?: Array<any>;
    /**
     * 
     * @type {Array<AlbumDto>}
     * @memberof SearchResponseDto
     */
    albums?: Array<AlbumDto>;
    /**
     * 
     * @type {Array<SongDto>}
     * @memberof SearchResponseDto
     */
    songs?: Array<SongDto>;
}

/**
 * Check if a given object implements the SearchResponseDto interface.
 */
export function instanceOfSearchResponseDto(value: object): value is SearchResponseDto {
    return true;
}

export function SearchResponseDtoFromJSON(json: any): SearchResponseDto {
    return SearchResponseDtoFromJSONTyped(json, false);
}

export function SearchResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'artists': json['artists'] == null ? undefined : json['artists'],
        'albums': json['albums'] == null ? undefined : ((json['albums'] as Array<any>).map(AlbumDtoFromJSON)),
        'songs': json['songs'] == null ? undefined : ((json['songs'] as Array<any>).map(SongDtoFromJSON)),
    };
}

export function SearchResponseDtoToJSON(json: any): SearchResponseDto {
    return SearchResponseDtoToJSONTyped(json, false);
}

export function SearchResponseDtoToJSONTyped(value?: SearchResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'artists': value['artists'],
        'albums': value['albums'] == null ? undefined : ((value['albums'] as Array<any>).map(AlbumDtoToJSON)),
        'songs': value['songs'] == null ? undefined : ((value['songs'] as Array<any>).map(SongDtoToJSON)),
    };
}

