/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SongDto
 */
export interface SongDto {
    /**
     * 
     * @type {string}
     * @memberof SongDto
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof SongDto
     */
    coverPath?: string;
    /**
     * 
     * @type {number}
     * @memberof SongDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SongDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SongDto
     */
    genre?: string;
    /**
     * 
     * @type {number}
     * @memberof SongDto
     */
    length?: number;
    /**
     * 
     * @type {string}
     * @memberof SongDto
     */
    audioPath?: string;
    /**
     * 
     * @type {string}
     * @memberof SongDto
     */
    albumName?: string;
    /**
     * 
     * @type {number}
     * @memberof SongDto
     */
    albumId?: number;
    /**
     * 
     * @type {string}
     * @memberof SongDto
     */
    artistName?: string;
}

/**
 * Check if a given object implements the SongDto interface.
 */
export function instanceOfSongDto(value: object): value is SongDto {
    return true;
}

export function SongDtoFromJSON(json: any): SongDto {
    return SongDtoFromJSONTyped(json, false);
}

export function SongDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SongDto {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'coverPath': json['coverPath'] == null ? undefined : json['coverPath'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'genre': json['genre'] == null ? undefined : json['genre'],
        'length': json['length'] == null ? undefined : json['length'],
        'audioPath': json['audioPath'] == null ? undefined : json['audioPath'],
        'albumName': json['albumName'] == null ? undefined : json['albumName'],
        'albumId': json['albumId'] == null ? undefined : json['albumId'],
        'artistName': json['artistName'] == null ? undefined : json['artistName'],
    };
}

export function SongDtoToJSON(json: any): SongDto {
    return SongDtoToJSONTyped(json, false);
}

export function SongDtoToJSONTyped(value?: SongDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'coverPath': value['coverPath'],
        'id': value['id'],
        'name': value['name'],
        'genre': value['genre'],
        'length': value['length'],
        'audioPath': value['audioPath'],
        'albumName': value['albumName'],
        'albumId': value['albumId'],
        'artistName': value['artistName'],
    };
}

